services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:akutengel2025@mongodb:27017/akutengel?authSource=admin
      - PORT=5000
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  #frontend:  # NEU
  #  build: ./frontend
  #  ports:
  #    - "5173:5173"
  #  environment:
  #    - VITE_API_URL=http://localhost:5000
  #  volumes:
  #    - ./frontend:/app
  #    - /app/node_modules
  #  depends_on:
  #    - backend

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=akutengel2025
      - MONGO_INITDB_DATABASE=akutengel
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongo_data: