version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: akutengel-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: akutengel2025
      MONGO_INITDB_DATABASE: akutengel
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - akutengel-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: akutengel-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:akutengel2025@mongodb:27017/akutengel?authSource=admin
      JWT_SECRET: akutengel-super-secret-jwt-key-change-in-production-2025
      JWT_EXPIRE: 7d
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - akutengel-network
    command: npm run dev

volumes:
  mongodb_data:
    driver: local

networks:
  akutengel-network:
    driver: bridge