version: '3.8'

services:
  backend:
    build: ./backend
    container_name: akutengel-backend-1
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:akutengel2025@mongodb:27017/akutengel?authSource=admin
      - PORT=5000
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - akutengel-network
    restart: unless-stopped
    # volumes ENTFERNT für Production-Build

  mongodb:
    image: mongo:7
    container_name: akutengel-mongodb-1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=akutengel2025
      - MONGO_INITDB_DATABASE=akutengel
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - akutengel-network
    restart: unless-stopped

networks:
  akutengel-network:
    driver: bridge

volumes:
  mongo_data: